baseurl: "http://ctfs.and.coffee/"
languageCode: "en-us"
title: "Dangerpwn"
theme: "detox"
buildDrafts: true
taxonomies:
  tag: "tags"
  author: "authors"

pygmentsStyle: "fruity"
pygmentsUseClasses: false
pygmentsCodeFences: false
pygmentsOptions: "nobackground=false,title=test"
