baseurl: "http://indefinite.space/"
languageCode: "en-us"
title: "Dangerpwn"
theme: "detox"
metaDataFormat: "yaml"
buildDrafts: false
taxonomies:
  tag: "tags"
  author: "authors"

pygmentsStyle: "fruity"
pygmentsUseClasses: false
pygmentsCodeFences: false
pygmentsOptions: "nobackground=false,title=test"
